# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('plate_Number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
