# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='plate_Number',
            new_name='plate_number',
        ),
    ]
