# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spot', '0003_parkinguser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parkinguser',
            table='pakring user',
        ),
    ]
